### ISSUE TITLE
Help: Setting up CloudNet

### ISSUE THREAD

**Issue by FrinshHD** [docimin/cloudnet-webinterface#21]
What do I need to setup in CloudNet to get the dashboard to work?

**Comment by docimin** [comment]
Hey,

It depends, do you want to use the hosted webinterface, or self hosted?

For Self-hosted, just follow the [README.md](https://github.com/docimin/cloudnet-webinterface/blob/main/README.md)
If you want to use the hosted version, you need your cloudnet to be publically available on https, for this you can use Reverse Proxy using Apache or NGINX.
