### ISSUE TITLE
Login  Data

### ISSUE THREAD

**Issue by EinfachMaiki** [docimin/cloudnet-webinterface#25]
Whats the Login Data to log into the Webinterface or how do i change them?

**Comment by docimin** [comment]
Hey,

You need CloudNet RC-11 or higher, create a rest user using the `rest` command. Give it the scope `global:admin` and you're good to go.

**Comment by EinfachMaiki** [comment]
Why isn't RC10 supported?

**Comment by 0utplay** [comment]
Because CloudNet RC10 is outdated and does not have all required rest api features
