### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheCGuyGitHub** [docimin/cloudnet-webinterface#8]
Hey, i have tryed to use your Webinterface and i know its still WIP, but if i try to Sign in, i get an error in the console.
I dont know if you know how to fix it or i have something configured wrong in cloudnet.
Here is a screenshot of the console if it helps.

![Screenshot from 2024-05-28 22-33-43](https://github.com/docimin/cloudnet-webinterface/assets/132585491/af7dbaae-1881-4fd8-86d6-e5a201ec00a2)

**Comment by docimin** [comment]
> Hey, i have tryed to use your Webinterface and i know its still WIP, but if i try to Sign in, i get an error in the console. I dont know if you know how to fix it or i have something configured wrong in cloudnet. Here is a screenshot of the console if it helps.
> 
> ![Screenshot from 2024-05-28 22-33-43](https://private-user-images.githubusercontent.com/132585491/334567916-af7dbaae-1881-4fd8-86d6-e5a201ec00a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjcwNzAsIm5iZiI6MTcxNjk2Njc3MCwicGF0aCI6Ii8xMzI1ODU0OTEvMzM0NTY3OTE2LWFmN2RiYWFlLTE4ODEtNGZkOC04NmQ2LWU1YTIwMWVjMDBhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwNzEyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTYzN2Q3N2RkODljNWM0MzkzNmY1NjNkOTdjMjgwZGViN2M0NTY2MzE4YTVhMzYwZTYyNjYxMTI5Yjk3M2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F95fC1nGAD-RbtntyQVi7MwdeqS8TqgoGC_NQAcIvSc)

Hey, thanks for your interest!

CloudNet RC-10 versions are only supported with a domain (https), not IP.

I see you tried to connect using an IP, this will be possible in one of the next releases.
Until then, either you need to use a domain instead of IP, or wait for one of the next releases.

Sorry for the inconvenience!
